module

public import Mathlib.RingTheory.DedekindDomain.SInteger

/-! Working copy of `IsDedekindDomain.exists_mul_algebraMap_eq_algebraMap` from #40848,
for discussing a more efficient proof. Verbatim copy to start from, renamed with a `'`. -/

@[expose] public section

open scoped nonZeroDivisors

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum Set

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
  (S : Set <| HeightOneSpectrum R) (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]

namespace IsDedekindDomain

variable (R)

open Ideal IsDedekindDomain.HeightOneSpectrum Set in
lemma exists_mul_algebraMap_eq_algebraMap' [Fact (IsMulTorsion (ClassGroup R))]
    (z : S.integer K) :
    ∃ x : R × Localization.submonoid S,
    z * algebraMap R (S.integer K) x.2 = algebraMap R (S.integer K) x.1 := by
  simp only [Prod.exists, Subtype.exists]
  -- Let `T` be the finite set of places that have `v(z) > 1`.
  let T := (Support.finite (R := R) (z : K)).toFinset
  -- `I` is the denominator ideal of `z`.
  let I := ∏ v ∈ T, v.asIdeal ^ (v.valuation K z).log.toNat
  have hI_ne_zero : I ≠ 0 := by
    grind [Finset.prod_ne_zero_iff, pow_ne_zero, HeightOneSpectrum.ne_bot, bot_eq_zero]
  /- Here we use the fact that the class group has finite order, so there exist `n > 0` and `α` such
  that `I ^ n` is generated by `α`. -/
  let I₀ : (Ideal R)⁰ := ⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne_zero⟩
  obtain ⟨n, hn, _⟩ := isOfFinOrder_iff_pow_eq_one.1
    ((Fact.out : IsMulTorsion (ClassGroup R)) (ClassGroup.mk0 I₀))
  obtain ⟨α, hα⟩ : (I ^ n).IsPrincipal := by
    simp_all [← MonoidHom.map_pow, ClassGroup.mk0_eq_one_iff, I₀]
  have hαz_valuation_le_one (v : HeightOneSpectrum R) :
      v.valuation K (algebraMap R K α * z) ≤ 1 := by
    let e := (v.valuation K z).log.toNat
    calc
    v.valuation K (algebraMap R K α * z) = v.valuation K (algebraMap R K α) * v.valuation K z :=  by
            rw [map_mul]
    _ ≤ WithZero.exp (-(e : ℤ)) * WithZero.exp (e : ℤ) := by
            apply mul_le_mul' _ <| WithZero.le_exp_of_log_le (Int.self_le_toNat _)
            simpa [valuation_of_algebraMap, intValuation_le_pow_iff_mem] using
              mem_prime_pow_of_span_eq_prod (R := R) K z hn.ne' hα.symm v
    _ = 1 := by simp [← WithZero.exp_add]
  -- we can write `z * α = β` for some `β ∈ R`.
  obtain ⟨β, hβ⟩ : ∃ β : R, z * algebraMap R K α = algebraMap R K β := by
    simpa [mul_comm, eq_comm] using
      mem_range.mp <| mem_integers_of_valuation_le_one (K := K) (algebraMap R K α * z)
        hαz_valuation_le_one
  refine ⟨β, α, ?_, SetLike.coe_eq_coe.mp hβ⟩
  -- we are left to prove that `α ∈ Localization.submonoid S`, i.e. that `α` is non-zero and not
  -- contained in any prime ideal not in `S`.
  simp only [Localization.submonoid, Submonoid.mem_inf, mem_sInfPrimeCompl_iff,
    mem_nonZeroDivisors_iff_ne_zero]
  refine ⟨?_, fun hα0 ↦ hI_ne_zero <| eq_zero_of_pow_eq_zero (by simpa [hα0] using hα)⟩
  rintro _ ⟨v, hvS, rfl⟩ _
  -- `α ∈ v.asIdeal` and `I ^ n = R ∙ α` imply that `v` is in `T`.
  have hvT : v ∈ T := by
    obtain ⟨w, hwT, hwle⟩ := v.isPrime.prod_le.1 <|
      IsPrime.le_of_pow_le (by rwa [hα, span_singleton_le_iff_mem v.asIdeal])
    simpa [HeightOneSpectrum.ext
      (w.isMaximal.eq_of_le v.isPrime.ne_top' (IsPrime.le_of_pow_le hwle))] using hwT
  apply hvS
  contrapose hvT
  simp [T, HeightOneSpectrum.Support, integer_valuation_le_one S K z hvS]


/-! ## Multiplicity-based variant

The idea: the only thing needed about the generator `α` of `I ^ n` is its multiplicity at each
`v`, namely `n * denomExponent z v`, the denominator exponent of `z` at `v` (zero off the
support). That single statement replaces both valuation computations of the original proof:

* `v (α z) ≤ 1` for all `v`, since `denomExponent z v ≤ n * denomExponent z v`;
* `α ∉ v.asIdeal` for `v ∉ S`, since `v ∉ T` gives multiplicity `0`.
-/

namespace Draft

open Ideal IsDedekindDomain.HeightOneSpectrum Set UniqueFactorizationMonoid

variable {R K}

/-- The denominator exponent of `z` at `v`. -/
noncomputable def denomExponent (z : K) (v : HeightOneSpectrum R) : ℕ :=
  (v.valuation K z).log.toNat

theorem denomExponent_eq_zero (z : K) {v : HeightOneSpectrum R} (hv : v ∉ Support R z) :
    denomExponent z v = 0 := by
  rw [denomExponent]
  refine Int.toNat_eq_zero.mpr ?_
  rw [WithZero.log_le_iff_le_exp, WithZero.exp_zero]
  rw [Support] at hv
  simpa using hv
  rw [Valuation.ne_zero_iff]
  

/-- The multiplicity of `v` in a generator of `I ^ n`, where `I` is the denominator ideal. -/
lemma emultiplicity_generator (z : K) {n : ℕ} {α : R}
    (hα : (∏ w ∈ (Support.finite (R := R) z).toFinset, w.asIdeal ^ denomExponent z w) ^ n =
    span {α}) (v : HeightOneSpectrum R) :
    emultiplicity v.asIdeal (span {α}) = n * denomExponent z v := by
  classical
  have h {w} : emultiplicity v.asIdeal w.asIdeal = if w = v then 1 else 0 := sorry
  rw [← congr_arg (emultiplicity v.asIdeal ·) hα]
  simp only [emultiplicity_pow v.prime, Finset.emultiplicity_prod v.prime]
  rw [Finset.sum_eq_single v (fun w _ hw ↦ ?_) ?_]
  · rw [h, ite_eq_left rfl, mul_one]
  · intro hv
    simp at hv

    sorry
  · rw [h, ite_eq_right hw, mul_zero]

#exit

  rw [← hα, emultiplicity_pow hv, Finset.emultiplicity_prod hv]
  have hterm (w : HeightOneSpectrum R) (hw : w ≠ v) :
      emultiplicity v.asIdeal (w.asIdeal ^ denomExponent z w) = 0 := by
    rw [emultiplicity_pow hv, emultiplicity_eq_zero.mpr, mul_zero]
    simpa [Ideal.dvd_iff_le, ← HeightOneSpectrum.ext_iff] using
      fun h ↦ hw (HeightOneSpectrum.ext (w.isMaximal.eq_of_le v.isPrime.ne_top' h))
  rw [Finset.sum_eq_single v (fun w _ hw ↦ hterm w hw) ?_]
  · rw [emultiplicity_pow hv,
      FiniteMultiplicity.emultiplicity_self (FiniteMultiplicity.of_prime_left hv v.ne_bot), mul_one]
  · intro hvT
    have hz : denomExponent z v = 0 := by
      by_cases h0 : z = 0
      · simp [denomExponent, h0]
      · have : v.valuation K z ≤ 1 := by
          simpa [HeightOneSpectrum.Support, Set.Finite.mem_toFinset] using hvT
        simp only [denomExponent, Int.toNat_eq_zero]
        exact (WithZero.log_le_iff_le_exp (by simpa using h0)).mpr (by simpa using this)
    simpa [hz, ← Ideal.one_eq_top] using emultiplicity_of_one_right hv.not_isUnit

/-- The two consequences used by the main proof, both immediate from the multiplicity. -/
lemma valuation_mul_le_one (z : K) {n : ℕ} (hn : n ≠ 0) {α : R}
    (h : ∀ v : HeightOneSpectrum R, emultiplicity v.asIdeal (span {α}) = n * denomExponent z v)
    (v : HeightOneSpectrum R) : v.valuation K (algebraMap R K α * z) ≤ 1 := by
  have h1 : v.intValuation α ≤ WithZero.exp (-(denomExponent z v : ℤ)) := by
    rw [intValuation_le_exp_iff_le_emultiplicity, h v]
    exact_mod_cast Nat.le_mul_of_pos_left _ (Nat.pos_of_ne_zero hn)
  calc v.valuation K (algebraMap R K α * z)
      = v.valuation K (algebraMap R K α) * v.valuation K z := by rw [map_mul]
    _ ≤ WithZero.exp (-(denomExponent z v : ℤ)) * WithZero.exp (denomExponent z v : ℤ) :=
        mul_le_mul' (by rwa [valuation_of_algebraMap])
          (WithZero.le_exp_of_log_le (Int.self_le_toNat _))
    _ = 1 := by simp [← WithZero.exp_add]

lemma notMem_of_e_eq_zero {α : R} {n : ℕ} (z : K)
    (h : ∀ v : HeightOneSpectrum R, emultiplicity v.asIdeal (span {α}) = n * denomExponent z v)
    {v : HeightOneSpectrum R} (hv : denomExponent z v = 0) : α ∉ v.asIdeal := by
  rw [← Ideal.dvd_span_singleton, ← emultiplicity_eq_zero, h v]
  simp [hv]

/-- The main statement, assembled from the three lemmas above. -/
lemma exists_mul_algebraMap_eq_algebraMap'' [Fact (IsMulTorsion (ClassGroup R))]
    (z : S.integer K) :
    ∃ x : R × Localization.submonoid S,
    z * algebraMap R (S.integer K) x.2 = algebraMap R (S.integer K) x.1 := by
  simp only [Prod.exists, Subtype.exists]
  let T := (Support.finite (R := R) (z : K)).toFinset
  let I := ∏ w ∈ T, w.asIdeal ^ denomExponent (z : K) w
  have hI_ne_zero : I ≠ 0 := by
    grind [Finset.prod_ne_zero_iff, pow_ne_zero, HeightOneSpectrum.ne_bot, bot_eq_zero]
  let I₀ : (Ideal R)⁰ := ⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne_zero⟩
  obtain ⟨n, hn, _⟩ := isOfFinOrder_iff_pow_eq_one.1
    ((Fact.out : IsMulTorsion (ClassGroup R)) (ClassGroup.mk0 I₀))
  obtain ⟨α, hα⟩ : (I ^ n).IsPrincipal := by
    simp_all [← MonoidHom.map_pow, ClassGroup.mk0_eq_one_iff, I₀]
  have hα0 : α ≠ 0 := fun h ↦ hI_ne_zero <| eq_zero_of_pow_eq_zero (by simpa [h] using hα)
  -- the single multiplicity statement that drives everything
  have hmult := emultiplicity_generator (z : K) (n := n) (α := α) hα
  -- `α z` is integral, so `α z = β` for some `β ∈ R`
  obtain ⟨β, hβ⟩ : ∃ β : R, z * algebraMap R K α = algebraMap R K β := by
    simpa [mul_comm, eq_comm] using
      mem_range.mp <| mem_integers_of_valuation_le_one (K := K) (algebraMap R K α * z)
        (valuation_mul_le_one (z : K) hn.ne' hmult)
  refine ⟨β, α, ?_, SetLike.coe_eq_coe.mp hβ⟩
  -- `α` lies in the submonoid: nonzero, and outside every prime away from `S`
  simp only [Localization.submonoid, Submonoid.mem_inf, mem_sInfPrimeCompl_iff,
    mem_nonZeroDivisors_iff_ne_zero]
  refine ⟨?_, hα0⟩
  rintro _ ⟨v, hvS, rfl⟩ hmem
  refine notMem_of_e_eq_zero (z : K) hmult ?_ hmem
  -- off `S`, the valuation of `z` is at most one, so the denominator exponent vanishes
  have h1 := integer_valuation_le_one S K z hvS
  by_cases hz : (z : K) = 0
  · simp [denomExponent, hz]
  · simp only [denomExponent, Int.toNat_eq_zero]
    exact (WithZero.log_le_iff_le_exp (by simpa using hz)).mpr (by simpa using h1)

end Draft

end IsDedekindDomain
