/-
Copyright (c) 2026 Xavier Roblot. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Xavier Roblot
-/
module

public import Mathlib.FieldTheory.Finite.Extension
public import Mathlib.NumberTheory.Cyclotomic.Gal
public import Mathlib.NumberTheory.DirichletCharacter.Basic
public import Mathlib.NumberTheory.MulChar.Duality
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
public import Mathlib.NumberTheory.NumberField.Ideal.Basic
public import Mathlib.NumberTheory.RamificationInertia.HilbertTheory
public import Mathlib.RingTheory.Ideal.Galois
public import Mathlib.NumberTheory.DirichletCharacter.Orthogonality

public import Mathlib.Sandbox

/-!
# Galois theory for cyclotomic fields

In this file, we study the Galois theory of cyclotomic extensions of `ℚ`.

Let `n` be an integer. There is an isomorphism between `Gal(ℚ(ζₙ)/ℚ)` and `(ℤ/nℤ)ˣ` that sends `σ`
to `a_σ` such that `σ (ζₙ) = ζₙ ^ a_σ`.

Following [Washington][washington.cyclotomic], we define the bijection between subfields
of `ℚ(ζₙ)` and subgroups of the group `Xₙ` of Dirichlet characters of level `n` such that
`F` corresponds to `Y` iff the subgroup `H` of `(ℤ/nℤ)ˣ` corresponding to `F` by the above
isomorphism is the orthogonal of `Y` for the nondegenerate pairing on `(ℤ/nℤ)ˣ × Xₙ`
defined by `(n, χ) ↦ χ n`.

## Main definitions and results

- `IsCyclotomicExtension.Rat.galEquivZMod`: the isomorphism between `Gal(ℚ(ζₙ)/ℚ)` and `(ℤ/nℤ)ˣ`
  that sends `σ` to the class `a` such that `σ (ζₙ) = ζₙ ^ a`.
- `IsCyclotomicExtension.Rat.isInertiaField`: if `n = p ^ k * m` with `p` prime and `¬ p ∣ m`, then
  `ℚ(ζₘ)` is the inertia field of any prime of `𝓞(ℚ(ζₙ))` lying over `p`.
- `IsCyclotomicExtension.Rat.intermediateFieldEquivSubgroupChar`: the bijection between the
  intermediate fields of `ℚ(ζₙ)/ℚ` and subgroups of `Xₙ`.
- `IsCyclotomicExtension.Rat.mem_intermediateFieldEquivSubgroupChar_iff`: assume that `m ∣ n`,
  then the image of `ℚ(ζₘ) ⊆ ℚ(ζₙ)` by `intermediateFieldEquivSubgroupChar` is the set of
  characters whose conductor divides `m`.
- `IsCyclotomicExtension.Rat.galEquivZMod_stabilizer`: assume that the prime `p` does not divide
  `n` then, for any prime ideal `P` above `p` in `ℚ(ζₙ)`, the image by `galEquivZMod` of the
  decomposition group of `P` is the cyclic subgroup of `(ℤ/nℤ)ˣ` generated by the Frobenius
  element `[p]`.

-/

@[expose] public section

namespace IsCyclotomicExtension.Rat

open NumberField IsCyclotomicExtension

variable (n : ℕ) [NeZero n] (K : Type*) [Field K] [NumberField K]
  [hK : IsCyclotomicExtension {n} ℚ K]

include hK in
/--
The isomorphism between `Gal(ℚ(ζₙ)/ℚ)` and `(ℤ/nℤ)ˣ` that sends `σ` to the class `a` such that
`σ (ζₙ) = ζₙ ^ a`.
-/
noncomputable abbrev galEquivZMod : Gal(K/ℚ) ≃* (ZMod n)ˣ :=
  IsCyclotomicExtension.autEquivPow K <| Polynomial.cyclotomic.irreducible_rat (NeZero.pos n)

theorem galEquivZMod_apply_of_pow_eq (σ : Gal(K/ℚ)) {x : K} (hx : x ^ n = 1) :
    σ x = x ^ (galEquivZMod n K σ).val.val := by
  obtain ⟨a, -, rfl⟩ := (zeta_spec n ℚ K).eq_pow_of_pow_eq_one hx
  rw [map_pow, pow_right_comm, galEquivZMod, autEquivPow_apply, OneHom.toFun_eq_coe,
    MonoidHom.toOneHom_coe, IsPrimitiveRoot.autToPow_spec]

set_option backward.isDefEq.respectTransparency false in
theorem galEquivZMod_smul_of_pow_eq (σ : Gal(K/ℚ)) {x : 𝓞 K} (hx : x ^ n = 1) :
    σ • x = x ^ (galEquivZMod n K σ).val.val := by
  apply FaithfulSMul.algebraMap_injective (𝓞 K) K
  apply galEquivZMod_apply_of_pow_eq n K σ <| by rw [← Subalgebra.coe_pow, hx, OneMemClass.coe_one]

section restrict

variable {m : ℕ} [NeZero m] (F : Type*) [Field F] [NumberField F]
  [hF : IsCyclotomicExtension {m} ℚ F] [Algebra F K] [IsGalois ℚ F]

/--
Let `m ∣ n`. Then, the following diagram commutes:
Gal(ℚ(ζₙ)/ℚ) → (ℤ/nℤ)ˣ
  ↓              ↓
Gal(ℚ(ζₘ)/ℚ) → (ℤ/mℤ)ˣ
where the horizontal maps are `galEquivZMod`, the left map is the restriction map and the right map
is the natural map.
-/
theorem galEquivZMod_restrictNormal_apply (h : m ∣ n) (σ : Gal(K/ℚ)) :
    galEquivZMod m F (σ.restrictNormal F) = ZMod.unitsMap h (galEquivZMod n K σ) := by
  have hζ := IsCyclotomicExtension.zeta_spec m ℚ F
  let ζ := IsCyclotomicExtension.zeta m ℚ F
  suffices ζ ^ (galEquivZMod m F (σ.restrictNormal F)).val.val = ζ ^ (galEquivZMod n K σ).val.val by
    rw [(hζ.isOfFinOrder (NeZero.ne _)).pow_inj_mod, ← hζ.eq_orderOf,
      ← ZMod.natCast_eq_natCast_iff', ZMod.natCast_val, ZMod.natCast_val, ZMod.cast_id] at this
    rwa [Units.ext_iff]
  apply FaithfulSMul.algebraMap_injective F K
  rw [map_pow, map_pow, ← galEquivZMod_apply_of_pow_eq, ← AlgEquiv.restrictNormal_commutes,
      galEquivZMod_apply_of_pow_eq m _ _ hζ.pow_eq_one, map_pow]
  rw [← map_pow, (hζ.pow_eq_one_iff_dvd _).mpr h, map_one]

end restrict

open Ideal

/--
Let `K = ℚ(ζₙ)` with `n = p ^ k * m` where `p` is prime and `¬ p ∣ m`. Then the subfield
`F = ℚ(ζₘ)` is the inertia field of any prime `P` of `𝓞 K` lying over `p`.
-/
theorem isInertiaField {m p k : ℕ} (hn : n = p ^ k * m) [hp : Fact (p.Prime)] (hm : ¬ p ∣ m)
    (F : IntermediateField ℚ K) [hF : IsCyclotomicExtension {m} ℚ F] (P : Ideal (𝓞 K))
    [P.IsMaximal] [P.LiesOver (span {(p : ℤ)})] :
    IsInertiaField ℚ K P F := by
  have : NeZero m := ⟨fun h ↦ by simp [h] at hm⟩
  have hp' : span {(p : ℤ)} ≠ ⊥ := by simpa using hp.out.ne_zero
  have : IsGalois ℚ K := isGalois {n} ℚ K
  let 𝓟F : Ideal (𝓞 F) := comap (algebraMap (𝓞 F) (𝓞 K)) P
  have : P.LiesOver 𝓟F := over_under P
  have : 𝓟F.IsPrime := IsPrime.under (𝓞 F) P
  have : 𝓟F.LiesOver (span {(p : ℤ)}) := under_liesOver_of_liesOver (𝓞 F) P (span {(p : ℤ)})
  have hPF : 𝓟F ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hp' _
  have h := ramificationIdx_eq_of_not_dvd p F 𝓟F hm
  refine (IntermediateField.isInertiaField_iff ℤ ℚ K P F (𝓞 F) 𝓟F hp').mpr ⟨?_, h⟩
  obtain rfl | hk := Nat.eq_zero_or_eq_succ_pred k
  · have : F = ⊤ := by
      convert IntermediateField.isCyclotomicExtension_eq {n} ℚ K _ _
      · rwa [hn, pow_zero, one_mul]
      · exact IsCyclotomicExtension.equiv {n} ℚ K IntermediateField.topEquiv.symm
    refine Nat.le_antisymm (ramificationIdx_le_finrank F K 𝓟F P) ?_
    rw [IntermediateField.finrank_eq_one_iff_eq_top.mpr this]
    exact Nat.one_le_iff_ne_zero.mpr <|
      Ideal.IsDedekindDomain.ramificationIdx_ne_zero_of_liesOver P hPF
  rw [hk] at hn
  suffices Module.finrank F K = p ^ k.pred * (p - 1) by
    have h' := ramificationIdx_algebra_tower' (span {(p : ℤ)}) 𝓟F P
    rwa [h, one_mul, ramificationIdx_eq n K P hn hm, ← this, eq_comm] at h'
  rw [← mul_right_inj' ((Module.finrank_pos (R := ℚ) (M := F)).ne'),
    Module.finrank_mul_finrank ℚ F K, finrank n, finrank m, hn, Nat.totient_mul,
    Nat.totient_prime_pow_succ hp.out, mul_comm]
  exact Nat.Coprime.pow_left k.pred.succ <| by rwa [hp.out.coprime_iff_not_dvd]

section stabilizer

open Pointwise MulAction Ideal

variable (p : ℕ) [hp : Fact (Nat.Prime p)] (P : Ideal (𝓞 K)) [P.IsMaximal]
  [P.LiesOver (Ideal.span {(p : ℤ)})]

attribute [local instance] Ideal.Quotient.field

theorem mem_zpowers_galEquivZMod_of_mem_stabilizer_of_coprime (hn : p.Coprime n) {σ : Gal(K/ℚ)}
    (hσ : σ ∈ stabilizer Gal(K/ℚ) P) :
    galEquivZMod n K σ ∈ Subgroup.zpowers (ZMod.unitOfCoprime p hn) := by
  have hζ := IsCyclotomicExtension.zeta_spec n ℚ K
  let τ := IsFractionRing.stabilizerHom Gal(K/ℚ) (Ideal.span {(p : ℤ)}) P
     (ℤ ⧸ span {(p : ℤ)}) (𝓞 K⧸ P) ⟨σ, hσ⟩
  have : CharP (ℤ ⧸ span {(p : ℤ)}) p := ringChar.of_eq <| Int.ringChar_idealQuot p
  have : Finite (𝓞 K⧸ P) := Ring.HasFiniteQuotients.finiteQuotient (NeZero.ne P)
  obtain ⟨i, hi⟩ := FiniteField.exists_forall_apply_eq_pow (ℤ ⧸ span {(p : ℤ)}) p (𝓞 K⧸ P) τ
  refine ⟨i, ?_⟩
  have h₀ : IsPrimitiveRoot (Ideal.Quotient.mk P hζ.toInteger) n := by
    refine hζ.toInteger_isPrimitiveRoot.idealQuotient_mk
      (by simpa using IsMaximal.ne_top inferInstance) ?_
    rw [Ideal.absNorm_eq_pow_inertiaDeg' _ hp.out]
    exact Nat.Coprime.pow_left _ hn
  have h₁ := IsFractionRing.stabilizerHom_apply_apply_mk Gal(K/ℚ) (Ideal.span {(p : ℤ)}) P
      (ℤ ⧸ span {(p : ℤ)}) (𝓞 K⧸ P) ⟨σ, hσ⟩ hζ.toInteger
  simp only [Algebra.algebraMap_self, RingHomCompTriple.comp_apply] at h₁
  specialize hi (Ideal.Quotient.mk P hζ.toInteger)
  rwa [h₁, Int.card_ideal_quot, galEquivZMod_smul_of_pow_eq n _ _
    (hζ.toInteger_isPrimitiveRoot.pow_eq_one), map_pow, (h₀.isOfFinOrder (NeZero.ne _)).pow_inj_mod,
    ← h₀.eq_orderOf, ← ZMod.natCast_eq_natCast_iff', Nat.cast_pow, ← ZMod.coe_unitOfCoprime p hn,
    ← Units.val_pow_eq_pow_val, ZMod.natCast_zmod_val, ← Units.ext_iff, eq_comm] at hi

theorem galEquivZMod_stabilizer_of_coprime (hn : p.Coprime n) :
    (galEquivZMod n K).mapSubgroup (stabilizer Gal(K/ℚ) P) =
      Subgroup.zpowers (ZMod.unitOfCoprime p hn) := by
  classical
  have : IsGalois ℚ K := IsCyclotomicExtension.isGalois {n} ℚ K
  apply SetLike.ext'
  refine Set.eq_of_subset_of_card_le ?_ ?_
  · rintro _ ⟨σ, hσ, rfl⟩
    exact mem_zpowers_galEquivZMod_of_mem_stabilizer_of_coprime n K p P hn hσ
  · replace hn : ¬ p ∣ n := (Nat.Prime.coprime_iff_not_dvd hp.out).mp hn
    rw [Fintype.card_eq_nat_card, Fintype.card_eq_nat_card, SetLike.coe_sort_coe, Nat.card_zpowers,
      MulEquiv.mapSubgroup_apply, Subgroup.coe_map]
    change _  ≤ Nat.card ((galEquivZMod n K).toEquiv '' _)
    rw [Nat.card_image_equiv, SetLike.coe_sort_coe, Ideal.card_stabilizer_eq (span {(p : ℤ)})
      (by simp [hp.out.ne_zero]), inertiaDegIn_eq_of_not_dvd p K hn,
      ramificationIdxIn_eq_of_not_dvd p K hn, one_mul, ← orderOf_injective _ Units.coeHom_injective,
      Units.coeHom_apply, ZMod.coe_unitOfCoprime]

set_option backward.isDefEq.respectTransparency false in
open IntermediateField Pointwise in
theorem galEquivZMod_stabilizer {k m : ℕ} (hn : n = p ^ k * m) (hm : p.Coprime m) :
    (galEquivZMod n K).mapSubgroup (stabilizer Gal(K/ℚ) P) =
      (Subgroup.zpowers (ZMod.unitOfCoprime p hm)).comap
        (ZMod.unitsMap (Dvd.intro_left (p ^ k) hn.symm)) := by
  have : NeZero m := ⟨by aesop⟩
  ext c
  obtain ⟨ζ, hζ⟩ := hK.1 rfl (NeZero.ne n)
  have hζ' := IsPrimitiveRoot.pow (NeZero.pos n) hζ hn
  let E := ℚ⟮ζ ^ p ^ k⟯
  have : IsAbelianGalois ℚ K := isAbelianGalois {n} ℚ K
  let P₀ := under (𝓞 E) P
  have := (IntermediateField.isCyclotomicExtension_singleton_iff_eq_adjoin m ℚ K E hζ').mpr rfl
  have : IsInertiaField ℚ K P E := isInertiaField n K hn (hp.out.coprime_iff_not_dvd.mp hm) E P
  have := galEquivZMod_stabilizer_of_coprime m E p P₀ hm
  rw [← this]
  have := galEquivZMod_restrictNormal_apply n K E (Dvd.intro_left (p ^ k) hn.symm)
    ((galEquivZMod n K).symm c)
  rw [MulEquiv.apply_symm_apply] at this
  rw [Subgroup.mem_comap]
  rw [← this]
  rw [@MulEquiv.coe_mapSubgroup]
  rw [@Subgroup.mem_map_equiv]
  rw [@MulEquiv.coe_mapSubgroup]
  rw [@Subgroup.mem_map_equiv]
  rw [@MulEquiv.symm_apply_apply]
  let D := (FixedPoints.intermediateField (stabilizer Gal(K/ℚ) P) : IntermediateField ℚ K)
  let : Algebra D E :=
    (inclusion (isDecompositionField_le_isInertiaField ℚ K P D E)).toRingHom.toAlgebra
  have : IsScalarTower (𝓞 D) (𝓞 E) (𝓞 K) := IsScalarTower.of_algebraMap_eq' rfl
  rw [IsDecompositionField.restrictNormal_mem_stabilizer_iff ℚ K P D (𝓞 D)]


    -- have := stabilizerMapOfLiesOver_surjective ℚ K F P P₀ ⟨τ, ?_⟩
    -- simp only [MulEquiv.mapSubgroup_apply, Subgroup.mem_map, mem_stabilizer_iff, MonoidHom.coe_coe,
    --   autEquivPow_apply, OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe]

end stabilizer

open MulChar DirichletCharacter IntermediateField MulAction Pointwise

variable (R : Type*) [CommRing R] [HasEnoughRootsOfUnity R (Monoid.exponent (ZMod n)ˣ)]

/--
The bijection between the subgroups of `Gal(ℚ(ζₙ)/ℚ)` and the subgroups of the group
of Dirichlet characters of level `n`.
-/
noncomputable def subgroupGalEquivSubgroupChar :
    Subgroup Gal(K/ℚ) ≃o (Subgroup (DirichletCharacter R n))ᵒᵈ :=
  (galEquivZMod n K).mapSubgroup.trans <| subgroupOrderIsoSubgroupMulChar (ZMod n) R

@[simp]
theorem mem_subgroupGalEquivSubgroupChar_iff (χ : DirichletCharacter R n) (H : Subgroup Gal(K/ℚ)) :
    χ ∈ (subgroupGalEquivSubgroupChar n K R H).ofDual ↔
      ∀ σ ∈ H, χ (galEquivZMod n K σ) = 1 := by
  simp [subgroupGalEquivSubgroupChar]

@[simp]
theorem mem_subgroupGalEquivSubgroupChar_symm_iff (σ : Gal(K/ℚ))
    (Y : Subgroup (DirichletCharacter R n)) :
    σ ∈ (subgroupGalEquivSubgroupChar n K R).symm (OrderDual.toDual Y) ↔
      ∀ χ ∈ Y, χ (galEquivZMod n K σ) = 1 := by
  simp only [subgroupGalEquivSubgroupChar, OrderIso.symm_trans_apply, MulEquiv.symm_mapSubgroup,
    MulEquiv.coe_mapSubgroup, Subgroup.mem_map_equiv, MulEquiv.symm_symm,
    mem_subgroupOrderIsoSubgroupMulChar_symm_iff]

variable [IsAbelianGalois ℚ K]

theorem card_subgroupGalEquivSubgroupChar (H : Subgroup Gal(K/ℚ)) :
    Nat.card (subgroupGalEquivSubgroupChar n K R H).ofDual = Nat.card (Gal(K/ℚ) ⧸ H) := by
  rw [subgroupGalEquivSubgroupChar, OrderIso.trans_apply, card_subgroupOrderIsoSubgroupMulChar]
  exact Nat.card_congr (QuotientGroup.congr _ _ (galEquivZMod n K) rfl).symm.toEquiv

/--
The bijection between the intermediate fields of `ℚ(ζₙ)/ℚ` and the subgroups of the group
of Dirichlet characters of level `n`.
-/
noncomputable def intermediateFieldEquivSubgroupChar :
    IntermediateField ℚ K ≃o Subgroup (DirichletCharacter R n) :=
  IsGalois.intermediateFieldEquivSubgroup.trans <|
      (subgroupGalEquivSubgroupChar n K R).dual.trans (OrderIso.dualDual _).symm

@[simp]
theorem mem_intermediateFieldEquivSubgroupChar_iff (F : IntermediateField ℚ K)
    (χ : DirichletCharacter R n) :
    χ ∈ intermediateFieldEquivSubgroupChar n K R F ↔
      ∀ σ : Gal(K/ℚ), σ ∈ F.fixingSubgroup → χ (galEquivZMod n K σ) = 1 := by
  simp [intermediateFieldEquivSubgroupChar]

/-- The cardinality of the subgroup of Dirichlet characters of level `n` associated to an
intermediate field `F` of `ℚ(ζₙ)/ℚ` equals the degree `[F : ℚ]`. -/
theorem card_intermediateFieldEquivSubgroupChar (F : IntermediateField ℚ K) :
    Nat.card (intermediateFieldEquivSubgroupChar n K R F) = Module.finrank ℚ F := by
  unfold intermediateFieldEquivSubgroupChar
  rw [OrderIso.trans_apply, OrderIso.trans_apply, OrderIso.dualDual_symm_apply,
    IsGalois.intermediateFieldEquivSubgroup_apply, OrderIso.dual_apply, OrderDual.ofDual_toDual,
    OrderDual.ofDual_toDual, card_subgroupGalEquivSubgroupChar, finrank_eq_fixingSubgroup_index,
    ← Subgroup.index_eq_card]

theorem index_intermediateFieldEquivSubgroupChar (F : IntermediateField ℚ K) :
    (intermediateFieldEquivSubgroupChar n K R F).index = Module.finrank F K := by
  rw [← mul_right_inj' (Module.finrank_pos (R := ℚ) (M := F)).ne', Module.finrank_mul_finrank,
    ← card_intermediateFieldEquivSubgroupChar n K R, Subgroup.card_mul_index,
    card_eq_card_units_of_hasEnoughRootsOfUnity, finrank n K, Nat.card_eq_fintype_card,
    ZMod.card_units_eq_totient]

theorem relIndex_intermediateFieldEquivSubgroupChar (F F' : IntermediateField ℚ K) [IsDomain R] :
    (intermediateFieldEquivSubgroupChar n K R F).relIndex
      (intermediateFieldEquivSubgroupChar n K R F') = Module.finrank ↥(F ⊓ F') F' := by
  have : IsScalarTower ↥(F ⊓ F') F' K := IsScalarTower.of_algebraMap_eq' rfl
  have : (intermediateFieldEquivSubgroupChar n K R F').index ≠ 0 := Subgroup.index_ne_zero_of_finite
  rw [← mul_left_inj' this, Subgroup.relIndex_mul_index', index_intermediateFieldEquivSubgroupChar,
    Module.finrank_mul_finrank, ← OrderIso.map_inf, index_intermediateFieldEquivSubgroupChar]

-- variable (m : ℕ) [NeZero m] (L : Type*) [Field L] [NumberField L] [IsAbelianGalois ℚ L]
--   [hL : IsCyclotomicExtension {m} ℚ L] [HasEnoughRootsOfUnity R (Monoid.exponent (ZMod m)ˣ)]

-- example [Algebra K L] (hm : n ∣ m) (F : IntermediateField ℚ K) : 1 = 0 := by
--   let e : K →ₐ[ℚ] L := Algebra.algHom ℚ K L
--   let F' := IntermediateField.map e F
--   let A := intermediateFieldEquivSubgroupChar m L R F'
--   let B := intermediateFieldEquivSubgroupChar n K R F
--   have : A = B.map (changeLevel hm) := by
--     have : Fintype A := sorry
--     have : Fintype (Subgroup.map (changeLevel hm) B) := sorry
--     rw [eq_comm, SetLike.ext'_iff]
--     apply Set.eq_of_subset_of_card_le
--     · intro _ h
--       rw [SetLike.mem_coe, Subgroup.mem_map] at h
--       obtain ⟨χ, hχ, rfl⟩ := h


--     · sorry

--     rintro ⟨χ, ⟨hχ, rfl⟩⟩ σ hσ
--     · intro χ hχ
--     rw [Subgroup.mem_map]
--     simp_rw [mem_intermediateFieldEquivSubgroupChar_iff]
--     refine ⟨?_, ?_⟩
--     · sorry
--     · rintro ⟨χ, ⟨hχ, rfl⟩⟩ σ hσ
--       rw [changeLevel_eq_cast_of_dvd]
--       convert hχ (σ.restrictNormal K) ?_
--       sorry
--       rw [IntermediateField.mem_fixingSubgroup_iff]
--       intro x hx
--       apply FaithfulSMul.algebraMap_injective K L
--       rw [AlgEquiv.restrictNormal_commutes]
--       rw [IntermediateField.mem_fixingSubgroup_iff] at hσ
--       rw [hσ]
--       unfold F'
--       -- This is in extendTop
--       sorry

set_option backward.isDefEq.respectTransparency false in
/--
Assume that `m ∣ n`, then the image of `ℚ(ζₘ) ⊆ ℚ(ζₙ)` by `intermediateFieldEquivSubgroupChar` is
the set of characters whose conductor divides `m`.
-/
theorem mem_intermediateFieldEquivSubgroupChar_iff_conductor_dvd (F : IntermediateField ℚ K)
    {m : ℕ} [NeZero m] [IsGalois ℚ F] [IsCyclotomicExtension {m} ℚ F] (hdiv : m ∣ n)
    (χ : DirichletCharacter R n) :
    χ ∈ intermediateFieldEquivSubgroupChar n K R F ↔ χ.conductor ∣ m := by
  simp_rw [← χ.mem_conductorSet_iff_conductor_dvd hdiv, χ.mem_conductorSet_iff,
    factorsThrough_iff_ker_unitsMap hdiv, mem_intermediateFieldEquivSubgroupChar_iff,
    SetLike.le_def, ← (galEquivZMod n K).forall_congr_right, MonoidHom.mem_ker,
    MulEquiv.toEquiv_eq_coe, EquivLike.coe_coe, ← (galEquivZMod_restrictNormal_apply n K F hdiv _),
    EmbeddingLike.map_eq_one_iff, AlgEquiv.restrictNormal_eq_one_iff,
    IntermediateField.mem_fixingSubgroup_iff, Units.ext_iff, toUnitHom_eq, coe_equivToUnitHom,
    Units.val_one]

set_option backward.isDefEq.respectTransparency false in
theorem intermediateFieldEquivSubgroupChar_isInertiaField (p : ℕ) [hp : Fact (p.Prime)]
    (E : IntermediateField ℚ K) (P : Ideal (𝓞 K)) [P.IsMaximal]
    [P.LiesOver (span {(p : ℤ)})] [hE : IsInertiaField ℚ K P E] :
    intermediateFieldEquivSubgroupChar n K R E = subgroupOfCoprimeConductor R n p := by
  have hp' : span {(p : ℤ)} ≠ ⊥ := by simpa using hp.out.ne_zero
  obtain ⟨k, m, hm, hn⟩ := Nat.exists_eq_pow_mul_and_not_dvd (NeZero.ne n) p hp.out.ne_one
  have hm' : m ∣ n := dvd_of_mul_left_eq (p ^ k) hn.symm
  have : NeZero m := ⟨by aesop⟩
  obtain ⟨ζ, hζ⟩ := hK.1 rfl (NeZero.ne n)
  have hζ' := IsPrimitiveRoot.pow (NeZero.pos n) hζ hn
  let E' := ℚ⟮ζ ^ p ^ k⟯
  have := (isCyclotomicExtension_singleton_iff_eq_adjoin m ℚ K E' hζ').mpr rfl
  have : IsGalois ℚ E' := IsCyclotomicExtension.isGalois {m} ℚ E'
  rw [← IsGalois.fixedField_fixingSubgroup E, (isInertiaField_iff_fixingSubgroup ℚ K P).mp hE,
    ← (isInertiaField_iff_fixingSubgroup ℚ K P).mp (isInertiaField n K hn hm E' P),
    IsGalois.fixedField_fixingSubgroup]
  ext χ
  rw [mem_intermediateFieldEquivSubgroupChar_iff_conductor_dvd n K R E' hm',
    mem_subgroupOfCoprimeConductor]
  refine ⟨fun h ↦ Nat.Coprime.of_dvd_right h ((Nat.Prime.coprime_iff_not_dvd hp.out).mpr hm),
    fun h ↦ ?_⟩
  have : χ.conductor ∣ p ^ k * m := hn ▸ χ.conductor_dvd_level
  rwa [Nat.Coprime.dvd_mul_left] at this
  exact Nat.Prime.coprime_pow_of_not_dvd hp.out <| (Nat.Prime.coprime_iff_not_dvd hp.out).mp h

set_option backward.isDefEq.respectTransparency false in
example [Nontrivial R] (p : ℕ) [hp : Fact (p.Prime)] (D : IntermediateField ℚ K)
    (P : Ideal (𝓞 K)) [P.IsMaximal] [P.LiesOver (span {(p : ℤ)})]
    [hD : IsDecompositionField ℚ K P D] :
    intermediateFieldEquivSubgroupChar n K R D = subgroupOfPrimitiveMapToOne R n p := by
  have hp' : span {(p : ℤ)} ≠ ⊥ := by simpa using hp.out.ne_zero
  obtain ⟨k, m, hm, hn⟩ := Nat.exists_eq_pow_mul_and_not_dvd (NeZero.ne n) p hp.out.ne_one
  have hm' : m ∣ n := dvd_of_mul_left_eq (p ^ k) hn.symm
  have : NeZero m := ⟨by aesop⟩
  have := galEquivZMod_stabilizer n K p P hn (hp.out.coprime_iff_not_dvd.mpr hm)
  simp at this
--  have := (subgroupOrderIsoSubgroupMulChar (ZMod n) R).congr_arg this
--  have := OrderDual.ofDual.congr_arg this
  unfold intermediateFieldEquivSubgroupChar
  simp [subgroupGalEquivSubgroupChar]
  rw [(isDecompositionField_iff_fixingSubgroup ℚ K P).mp hD]
  rw [this]
  ext χ
  simp only [mem_subgroupOrderIsoSubgroupMulChar_iff, Subgroup.mem_comap,
    mem_subgroupOfPrimitiveMapToOne_iff]




  refine ⟨?_, ?_⟩
  · intro h
    obtain ⟨a, ha⟩ := ZMod.unitsMap_surjective (Dvd.intro_left (p ^ k) hn.symm)
      (ZMod.unitOfCoprime p (hp.out.coprime_iff_not_dvd.mpr hm))
    obtain ⟨x, hx⟩ := ZMod.intCast_surjective a.val
    have : (p : ZMod χ.conductor) = x := by
      refine (ZMod.natCast_eq_iff χ.conductor p ↑x).mpr ?_
      sorry
    rw [this, χ.primitiveCharacter_apply_of_isCoprime, hx]
    exact h a ⟨1, by simp [ha]⟩
    refine IsCoprime.symm ((fun n m ↦ (ZMod.coe_int_isUnit_iff_isCoprime n m).mp) x n ?_)

    rw [hx]
    exact Units.isUnit a

#exit

    have hχ : χ.conductor ∣ m := sorry


    have t0 := Units.ext_iff.mp ha
    have t1 := (ZMod.castHom hχ (ZMod χ.conductor)).congr_arg t0
    simp only [ZMod.castHom_apply, ZMod.coe_unitOfCoprime, map_natCast] at t1
    rw [← t1]

    obtain ⟨x, hx⟩ := ZMod.intCast_surjective a.val
    rw [← hx] at this
    rw [← χ.primitiveCharacter_apply_of_isCoprime] at this
    have t0 : χ.conductor ∣ n := sorry
    have t1 := (ZMod.castHom t0 (ZMod χ.conductor)).congr_arg hx
    simp at t1
    rw [t1] at this

    let f : ℤ →+* ZMod m := by exact Int.castRingHom (ZMod m)
    have : Function.Surjective ((↑) : ℤ → ZMod m) := by exact ZMod.intCast_surjective

    have : χ.conductor ∣ m := sorry
    rw [Units.ext_iff] at ha
    rw [ZMod.coe_unitOfCoprime] at ha
    have := (ZMod.castHom this (ZMod χ.conductor)).congr_arg ha
    simp at this
    rw [← this]

    rw [ZMod.unitsMap_val]
    rw [χ.primitiveCharacter_apply_of_isCoprime]
    convert this
    rw [@ZMod.intCast_cast]
    rw?
    sorry


  ·
    sorry



  rw [← IsGalois.fixedField_fixingSubgroup D, (isDecompositionField_iff_fixingSubgroup ℚ K P).mp hD,
    intermediateFieldEquivSubgroupChar]
  rw [OrderIso.trans_apply]
  rw [IsGalois.intermediateFieldEquivSubgroup_apply]
  rw [@OrderIso.trans_apply]
  rw [@OrderIso.dualDual_symm_apply]
  rw [@OrderIso.dual_apply]
  rw [@OrderDual.ofDual_toDual]



  rw [mem_subgroupOfPrimitiveMapToOne_iff]
  obtain ⟨ζ, hζ⟩ := hK.1 rfl (NeZero.ne n)
  have hζ' := IsPrimitiveRoot.pow (NeZero.pos n) hζ hn
  let E := ℚ⟮ζ ^ p ^ k⟯
  have := (isCyclotomicExtension_singleton_iff_eq_adjoin m ℚ K E hζ').mpr rfl
--  have : IsGalois ℚ E := IsCyclotomicExtension.isGalois {m} ℚ E
  have : D ≤ E := sorry

  ext χ
  rw [mem_subgroupOfPrimitiveMapToOne_iff, mem_intermediateFieldEquivSubgroupChar_iff,
    (isDecompositionField_iff_fixingSubgroup ℚ K P).mp hD,
    ← (galEquivZMod n K).symm.toEquiv.forall_congr_right]
  simp_rw [MulEquiv.toEquiv_eq_coe, MulEquiv.toEquiv_symm, MulEquiv.coe_toEquiv_symm]
  simp_rw [← Subgroup.mem_map_equiv, ← MulEquiv.coe_mapSubgroup, MulEquiv.apply_symm_apply]
  simp_rw [galEquivZMod_stabilizer n K p P sorry, MulEquiv.apply_symm_apply]
  convert_to χ (ZMod.unitOfCoprime p sorry : (ZMod n)ˣ) = 1 ↔ χ.primitiveCharacter p = 1
  · sorry
  rw [ZMod.coe_unitOfCoprime, ← Int.cast_natCast, ← primitiveCharacter_apply_of_isCoprime χ,
    Int.cast_natCast]





  sorry



set_option backward.isDefEq.respectTransparency false in
theorem ramificationIdxIn_eq_relIndex [IsDomain R] (F : IntermediateField ℚ K) {p : ℕ}
    [hp : Fact (p.Prime)] :
    ramificationIdxIn (span {(p : ℤ)}) (𝓞 F) =
      (subgroupOfCoprimeConductor R n p).relIndex (intermediateFieldEquivSubgroupChar n K R F) := by
  have hp' : span {(p : ℤ)} ≠ ⊥ := by simpa using hp.out.ne_zero
  obtain ⟨Q, _, _⟩ := Ideal.exists_maximal_ideal_liesOver_of_isIntegral (S := 𝓞 K) (span {(p : ℤ)})
  let P : Ideal (𝓞 F) := under (𝓞 F) Q
  let E := (FixedPoints.intermediateField (inertia Gal(K/ℚ) Q) : IntermediateField ℚ K)
  have : IsInertiaField ℚ F P ↥(E ⊓ F) := sorry
  rw [← IsInertiaField.rank_left ℤ ℚ F P ↥(E ⊓ F)]
  rw [← relIndex_intermediateFieldEquivSubgroupChar n K R]
  rw [intermediateFieldEquivSubgroupChar_isInertiaField n K R p E Q]
  exact hp'

#exit

  rw [← Ideal.card_inertia_eq_ramificationIdxIn _ hp' P (G := Gal(F/ℚ))]

set_option backward.isDefEq.respectTransparency false in
theorem ramificationIdxIn_eq_relIndex' (F : IntermediateField ℚ K) {p : ℕ} [hp : Fact (p.Prime)] :
    ramificationIdxIn (span {(p : ℤ)}) (𝓞 F) =
      (subgroupOfCoprimeConductor R n p).relIndex (intermediateFieldEquivSubgroupChar n K R F) := by
  have hp' : span {(p : ℤ)} ≠ ⊥ := by simpa using hp.out.ne_zero
  obtain ⟨k, m, hm, hn⟩ := Nat.exists_eq_pow_mul_and_not_dvd (NeZero.ne n) p hp.out.ne_one
  have : NeZero m := ⟨by aesop⟩
  obtain ⟨ζ, hζ⟩ := hK.1 rfl (NeZero.ne n)
  have hζ' := IsPrimitiveRoot.pow (NeZero.pos n) hζ hn
  let E := ℚ⟮ζ ^ p ^ k⟯
  have := (isCyclotomicExtension_singleton_iff_eq_adjoin m ℚ K E hζ').mpr rfl
  obtain ⟨Q, _, _⟩ := Ideal.exists_maximal_ideal_liesOver_of_isIntegral (S := 𝓞 K) (span {(p : ℤ)})
  let P : Ideal (𝓞 F) := under (𝓞 F) Q
  rw [← Ideal.card_inertia_eq_ramificationIdxIn _ hp' P (G := Gal(F/ℚ))]
  rw [Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective
    (Ideal.inertiaMapOfLiesOver ℚ K F Q P)
      (inertiaMapOfLiesOver_surjective ℚ K F Q P (span {(p : ℤ)}))).symm.toEquiv]
  rw [Nat.card_congr <| Subgroup.quotientEquivOfEq (inertiaMapOfLiesOver_ker ℚ K Q P F)]
  rw [← Subgroup.index_eq_card]
  rw [← Subgroup.relIndex]
  rw [← Subgroup.relIndex_map_map_of_injective _ _ (galEquivZMod n K).injective]
  rw [← relIndex_subgroupOrderIsoSubgroupMulChar (R := R)]
  rw [← (isInertiaField_iff_fixingSubgroup ℚ K Q).mp (isInertiaField n K hn hm E Q)]
  change ((intermediateFieldEquivSubgroupChar n K R E).subgroupOf
      (intermediateFieldEquivSubgroupChar n K R F)).index = _
  congr with χ
  rw [mem_intermediateFieldEquivSubgroupChar_iff_conductor_dvd n K R E
    (Dvd.intro_left (p ^ k) hn.symm), mem_subgroupOfCoprimeConductor]
  refine ⟨fun h ↦ Nat.Coprime.of_dvd_right h ((Nat.Prime.coprime_iff_not_dvd hp.out).mpr hm),
    fun h ↦ ?_⟩
  have : χ.conductor ∣ p ^ k * m := hn ▸ χ.conductor_dvd_level
  rwa [Nat.Coprime.dvd_mul_left] at this
  exact Nat.Prime.coprime_pow_of_not_dvd hp.out <| (Nat.Prime.coprime_iff_not_dvd hp.out).mp h

open  Pointwise

set_option backward.isDefEq.respectTransparency false in
example [Nontrivial R] (F : IntermediateField ℚ K) {p : ℕ} [hp : Fact (p.Prime)] :
    ramificationIdxIn (span {(p : ℤ)}) (𝓞 F) * inertiaDegIn (span {(p : ℤ)}) (𝓞 F) =
      (subgroupOfPrimitiveMapToOne R n p).relIndex
        (intermediateFieldEquivSubgroupChar n K R F) := by
  have hp' : span {(p : ℤ)} ≠ ⊥ := by simpa using hp.out.ne_zero
  obtain ⟨k, m, hm, hn⟩ := Nat.exists_eq_pow_mul_and_not_dvd (NeZero.ne n) p hp.out.ne_one
  have : NeZero m := ⟨by aesop⟩
  obtain ⟨ζ, hζ⟩ := hK.1 rfl (NeZero.ne n)
  have hζ' := IsPrimitiveRoot.pow (NeZero.pos n) hζ hn
  let E := ℚ⟮ζ ^ p ^ k⟯
  have := (isCyclotomicExtension_singleton_iff_eq_adjoin m ℚ K E hζ').mpr rfl
  obtain ⟨Q, _, _⟩ := Ideal.exists_maximal_ideal_liesOver_of_isIntegral (S := 𝓞 K) (span {(p : ℤ)})
  let P : Ideal (𝓞 F) := under (𝓞 F) Q
  let D := (FixedPoints.intermediateField (stabilizer Gal(K/ℚ) Q) : IntermediateField ℚ K)
  have : IsDecompositionField ℚ F P ↥(D ⊓ F) := sorry
  have : D ⊓ F ≤ E := sorry
  have : IsDecompositionField ℚ F P ↥(E ⊓ D ⊓ F) := sorry
  have := IsDecompositionField.rank_left ℤ ℚ F P ↥(E ⊓ D ⊓ F) (p := span {(p : ℤ)}) ?_
  rw [← this]


  sorry

end IsCyclotomicExtension.Rat
